// angular/face-capture/src/app/app.component.ts
import { Component } from '@angular/core';
import '@regulaforensics/vp-frontend-face-components';
import { FaceCaptureDetailType } from '@regulaforensics/vp-frontend-face-components';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    isOpen: boolean = false;

    faceCaptureHandler(data: CustomEvent<FaceCaptureDetailType>) {
        if (data.detail.action === 'PROCESS_FINISHED') {
            if (data.detail.data?.status === 1 && data.detail.data.response) {
                console.log(data.detail.data.response);
            }
        }

        if (data.detail?.action === 'CLOSE') {
            this.isOpen = false;
        }
    }
}

<div class="container" (face-capture)="faceCaptureHandler($event)">
    <face-capture *ngIf="isOpen; else openButton" start-screen></face-capture>
    <ng-template #openButton>
        <button (click)="isOpen = true">Open component</button>
    </ng-template>
</div>

// react-ts/face-capture/App.tsx
import * as React from 'react';
import { FaceCaptureDetailType } from '@regulaforensics/vp-frontend-face-components';

const containerStyle = {
    display: 'flex',
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
} as React.CSSProperties;

const buttonStyle = {
    padding: '10px 30px',
    color: 'white',
    fontSize: '16px',
    borderRadius: '2px',
    backgroundColor: '#bd7dff',
    border: '1px solid #bd7dff',
    cursor: 'pointer',
} as React.CSSProperties;

function App() {
    const [isOpen, setIsOpen] = React.useState(false);
    const containerRef = React.useRef<HTMLDivElement>(null);
    const listener = (data: CustomEvent<FaceCaptureDetailType>) => {
        if (data.detail.action === 'PROCESS_FINISHED') {
            if (data.detail.data?.status === 1 && data.detail.data.response) {
                console.log(data.detail.data.response);
            }
        }

        if (data.detail?.action === 'CLOSE') {
            setIsOpen(false);
        }
    };

    React.useEffect(() => {
        const containerCurrent = containerRef.current;

        if (!containerCurrent) return;

        containerCurrent.addEventListener('face-capture', listener);

        return () => {
            containerCurrent.removeEventListener('face-capture', listener);
        }
    }, []);

    return (
        <div style={containerStyle} ref={containerRef}>
            {isOpen ? (
                <face-capture start-screen></face-capture>
            ) : (
                <button style={buttonStyle} onClick={() => setIsOpen(true)}>Open component</button>
            )}
        </div>
    );
}

export default App;
